### PR TITLE
Cotribute RL

### PR DESCRIPTION
**Pull request by david1309**
Hello,
1. I had some doubst regarding if the equation (not the results) used to solved Policy Evaluation are correct
2. It would be nice to add at the end of Policy Iteration a mini-simulation that your policy indeed works on grid world

### CODE REVIEW

**Comment by dennybritz** [comment]
Regarding Policy Evaluation I may be wrong, but I think both solutions are correct, depending on whether or not the reward is stochastic or not. In Sutton's book (p. 79) it is multiplied by transition probability. If the reward is not stochastic (i.e. it only depends on s,a) then your solution and my solution should be equivalent because the transition probabilities sum to 1. I think mine is strictly more general and allows for stochastic reward.

**Comment by david1309** [comment]
I think the same as you, both solutions are correct for a non-stochastic MDP. However, a general equation should encompass both the stochastic and non-stochastic MDP. I think  the equation I implemented covers both scenarios while yours only covers the deterministic case. Since in a stochastic case the immediate reward R which for a given [s,a] should only be summed in the equation once, would be summed several times with different scalings since each Prob. would have some value != 0   e.g. 0.2*R + 0.8*R ... or  what do you think ?

**Comment by fferreres** [comment]
Unrelated to this fix, there's a typo (or bug?) in the MC chapter, off policy method, greedy policy function here (action vs acton)....

best_acton = np.argmax(Q[state])

Need to learn how to use git better. I know it's not to go here. I promise to look into git, but I've never done a pull request (not even a sync, only cloning)

**Comment by david1309** [comment]
ill have a look at it @fferreres  ... and don't worry about the git use, I am also a big noob at this. I could do some pull request, commits , and forks because I read this https://guides.github.com/ along with some cheat sheets ... little by little youll learn :)

**Comment by fferreres** [comment]
Yeah, I need to learn it immediately, but also Jupyter. The same function that has the typo is also taking an argument "observation"  but the code uses "state". Need to use state everywhere (as the state is what is passed):

   def policy_fn(state): # changed to state
        A = np.zeros_like(Q[state], dtype=float)
        best_action = np.argmax(Q[state]) # changed to best_action
        A[best_action] = 1.0
        return A
    return policy_fn

**Comment by dennybritz** [comment]
I still think that my solution is correct in both cases and that it is more general than your fix. I'm closing this for now. I may be wrong though, so if you can come up with an example where yours is correct and mine is incorrect please re-open this and I'll look at it again.

**Pull request closed without merging**
