### PR TITLE
Function description update for clarity. 

### PR DESCRIPTION
**Pull request by BAILOOL**
1. Synchronized function descriptions across multiple files.
2. Lambda -> gamma (discount factor) to avoid confusion for the reader.
3.  Added description of env.nS and env.nA. It might seem unclear for the beginner.

### CODE REVIEW

**Comment by BAILOOL** [comment]
1. Update function description in DP. 
2. Fixed typos in MC. 
3. Changed "Lambda" to "Gamma" as in the book.

**Comment by dennybritz** [comment]
It looks good, but it seems like all the Python versions have changed from Python 3 to Python 2...

**Comment by BAILOOL** [comment]
@dennybritz , sorry for that. Didn't realize my kernel was set to version 2. Thank you for the awesomely clean collection of materials for RL. I am going slowly through it. Enjoying conciseness quite a lot!

**Comment by dennybritz** [comment]
Thanks a lot, the changes look great.

**Pull request merged**
