### PR TITLE
Fixed the typo

### PR DESCRIPTION
**Pull request by ZuzooVn**

### CODE REVIEW

**Comment by dennybritz** [comment]
Thanks! Most of these look good, but two aren't right. Would be great if you could fix it and I'll merge.

**Comment by ZuzooVn** [comment]
Please comment to the wrong point. I will fix it.

**Comment by dennybritz** [comment]
Sorry for the delay, I thought I submitted the comment but I had to click the extra button ;)

**Comment by ZuzooVn** [comment]
I fixed them all.

**Pull request merged**
